Vagrant.configure("2") do |config|
    config.vm.box = "generic/alpine319"
    config.vm.provider "virtualbox" do |vb|
        vb.name = "brguicho"
        vb.memory = "512"
        vb.cpus = 1
        vb.gui = false
    end
    config.vm.define "brguichoS" do |brguichoS|
        brguichoS.vm.provider "virtualbox" do |vb|
            vb.name = "brguichoS"
            vb.memory = "2048"
            vb.cpus = 1
            vb.gui = false
        end
        brguichoS.vm.hostname = "brguichoS"
        brguichoS.vm.network "private_network", ip: "192.168.56.110"

        brguichoS.vm.provision "shell", name: "cgroup setup", path: "scripts/cgroup-setup.sh"
        brguichoS.vm.provision :reload
        brguichoS.vm.provision "shell", name: "K3s server", path: "scripts/k3s-controler.sh"
    end
    config.vm.define "brguichoSW" do |brguichoSW|
        brguichoSW.vm.provider "virtualbox" do |vb|
            vb.name = "brguichoSW"
            vb.memory = "512"
            vb.cpus = 1
            vb.gui = false
        end
        brguichoSW.vm.hostname = "brguichoSW"
        brguichoSW.vm.network "private_network", ip: "192.168.56.111"
        brguichoSW.vm.provision "shell", name: "cgroup setup", path: "scripts/cgroup-setup.sh"
        brguichoSW.vm.provision :reload
        brguichoSW.vm.provision "shell", name: "K3s agent mode", path: "scripts/k3s-agent.sh"
    end
end 