apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: iot-bonus-cluster
ports:
  - port: 8889:80
    nodeFilters:
      - loadbalancer
  - port: 8081:80
    nodeFilters:
      - loadbalancer
  - port: 8443:443
    nodeFilters:
      - loadbalancer